### ISSUE TITLE
issue in build

### ISSUE THREAD

**Issue by Aneeqasif** [emericg/MiniVideoInfos#1]
hy i am getting this issue on building it i am using majaro linux and pyhton version Python 3.10.5

```bash
> Building minivideo
-- * memfd enabled
-- > This is a RELEASE build.
-- Building with GCC compiler
-- Building on Linux plateform
** Building shared library
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/build/linux_x86_64/MiniVideo-master/minivideo/build
ninja: no work to do.
[0/1] Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/lib/libminivideo.so.0.14.0
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/lib/libminivideo.so.0
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/lib/libminivideo.so
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_export.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_avutils.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_codecs.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_containers.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_fourcc.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_twocc.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_uuid.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_mediafile.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_mediastream.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_metadata_vendors.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_settings.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/include/minivideo_typedef.h
-- Up-to-date: /home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/env/linux_x86_64/usr/lib/pkgconfig/libminivideo.pc

> Building QtLocation (patched)
Traceback (most recent call last):
  File "/home/aneeq/Downloads/git_down/MiniVideoInfos/contribs/contribs_builder.py", line 451, in <module>
    subprocess.check_call([QT_CONF_MODULE_cmd, ".."], cwd=build_dir + DIR_qtlocation + "/build")
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/6.3.1/gcc_64/bin/qt-configure-module'
```

**Comment by emericg** [comment]
Yes building QtLocation, not yet supported in Qt6, require Qt 6.3.0 / 6.3.1 and expects a Qt installation from the official installer. I can probably improve that tomorrow.

You can simply ignore building qtlocation and build just the others with that command:
```
contribs_builder.py --softwares taglib,libexif,minivideo
```
Also, remove 'location' in the MiniVideoInfos.pro `QT += core qml quickcontrols2 svg widgets charts location` line

And you will need to specify qmake to use library froms contribs instead of searching in already installed library, I forgot that in the README
```
qmake DEFINES+=USE_CONTRIBS
```

You may also have to remove the MobileUI file from `src/thirdparty/MobileUI/` (the one without extension) and adapt the corresponding include in the main.cpp (to use MobileUI.h this time). I saw that bug today and I'm not yet sure why it sometimes causes an issue.

I don't know if manjaro has access to the AUR packages? I can also pretty easily put everything directly there tomorrow if you are interested.

**Comment by emericg** [comment]
You can try with the  minivideoinfos-git package from the AUR, or otherwise I improved the README and fixed the MobileUI issue (maybe). Let me know how it goes.

**Comment by Aneeqasif** [comment]
i installed the pakage through AUR but i cant launch it
here is the error
```bash
/usr/bin/minivideoinfos
QQmlApplicationEngine failed to load component
qrc:/qml/Application.qml:141:5: Type MobileHeader unavailable
qrc:/qml/MobileHeader.qml:51:13: Type IconSvg unavailable
qrc:/qml/IconSvg.qml:4:1: module "Qt5Compat.GraphicalEffects" is not installed
```

**Comment by emericg** [comment]
You are probably just missing `qt6-5compat`. Maybe there are others dependencies I haven't properly listed yet.

**Comment by emericg** [comment]
And qt6-svg

**Comment by Aneeqasif** [comment]
got it build from aur. worked perfectly just a small issue was the all of the window content was not fitting to my screen
![image](https://user-images.githubusercontent.com/78728701/176032771-0cca7d0a-31de-4073-9e32-dadb1afc7f8d.png)
![image](https://user-images.githubusercontent.com/78728701/176032818-c759d9fa-124d-428f-af59-57b13d3eb45e.png)
![image](https://user-images.githubusercontent.com/78728701/176032924-48515ecc-4549-4503-be8d-e118b31000b0.png)

u can see in 3rd screenshot the lower content

**Comment by emericg** [comment]
Alright thanks for testing!
Looks like you have a tiny screen, and the "minimum height" was higher than its size, so I've reduced it to 640 px. You can simply reinstall the AUR package to get the fix.

This software isn't really made for desktops, as you can see the UI is very mobile oriented.
Technically it works, it's set to the tablet UI, it has drag and drops support. I fixed the file chooser today, and I'm starting to implement selectable text fields (so info can be easily copy pasted).
I'm still thinking about what a desktop version of this app should look and behave. If you have any comments, please let me know.

For a "true" desktop experience, you can have a look at https://github.com/emericg/MiniVideo/tree/master/mini_analyser
And download the AppImage from https://github.com/emericg/MiniVideo/actions/runs/2161308840
